Support unmap operation
rancher/liblonghorn pull request #17
Opened 2022-09-08 03:00 UTC by shuo-wu

Longhorn/longhorn#836

2022-09-15 12:18 UTC, innobead requested changes
LGTM, just one suggestion needed to resolve.

2022-09-15 12:18 UTC, innobead commented on src/longhorn_rpc_protocol.h
> +	TypeUnmap,
Suggest appending `TypeUnmap` to the last value of this enum, because the order of enum values could matter for backward compatibility somehow.

2022-11-07 06:29 UTC, innobead requested changes
LGTM, but only one comment needed to resolve.

2022-11-07 08:27 UTC, shuo-wu commented on src/longhorn_rpc_protocol.h
> +	TypePing,
NO. But it's a type of operation used in the dataconn server. Shouldn't we list all operations here?

2022-11-07 08:32 UTC, innobead approved these changes

2022-11-07 08:32 UTC, merged